apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: bitwarden-cli
  labels:
    app.kubernetes.io/instance: bitwarden-cli
    app.kubernetes.io/name: bitwarden-cli